apiVersion: v1
kind: Pod
metadata:
  name: wordcount3
spec:
  restartPolicy: OnFailure
  containers:
  - name: wc
    image: hibench-docker-opensource
    command: ["/bin/sh"]
    args: ["/root/runexample.sh", "1in1"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: hostvol
        mountPath: /root/time_cost
  volumes:
    - name: hostvol
      hostPath:
        path: /users/SuwenTC/concost/k8s/big_data/time_cost
 