apiVersion: v1
kind: Pod
metadata:
  name: wordcount2
spec:
  restartPolicy: OnFailure
  containers:
  - name: wc
    image: hibench-docker-opensource
    command: ["/bin/sh"]
    args: ["/root/runexample.sh", "5in5_2"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: hostvol
        mountPath: /root/time_cost
  volumes:
    - name: hostvol
      hostPath:
        path: /home/sgu21/concost/k8s/big_data/wordcount/time_cost
 