apiVersion: v1
kind: Pod
metadata:
    name: database17
spec:
  containers:
  - image: suwenbrucegu/mysql
    name: mysql
    imagePullPolicy: Never   
    env:
      # Use secret in real usage
    - name: MYSQL_ROOT_PASSWORD
      value: "1234"