apiVersion: v1
kind: Pod
metadata:
  name: vae3
spec:
  restartPolicy: OnFailure
  containers:
  - name: vae1
    image: vae
    command: ["./run.sh"]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "3"